name: Sync docs on change

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  sync:
    uses: ./.github/workflows/sync-docs-to-kitops.yml
    secrets:
      KITOPS_BOT_PRIVATE_KEY: ${{ secrets.KITOPS_BOT_PRIVATE_KEY }}
